### PR TITLE
Fix bug#1086234

### PR DESCRIPTION
**Pull request by emagana-zz**
Change the COE configuration from sqlite to mysql

### CODE REVIEW

**Comment by markvoelker** [comment]
So how does this make Glance use MySQL?  E.g. where is the default overridden?

**Comment by emagana-zz** [comment]
in the site.pp I added a glance_sql_connection variable that points to mysql
I have that commit waiting to get the other folsom-manifests pull requests in, as I said previously I can not pull request a new one until the previous are merged.

**Comment by markvoelker** [comment]
Ok, so this is just part one of two then.  LGTM then.

**Comment by rickerc** [comment]
looks good, merged

**Pull request merged**
