### PR TITLE
adding force_config_drive support

### PR DESCRIPTION
**Pull request by rakshithh**
adding force_config_drive support

ref: https://blueprints.launchpad.net/openstack-cisco/+spec/config-drive-support

### CODE REVIEW

**Comment by robertstarmer** [comment]
agree with Ian. Make the default false, and I'll give it the thumbs up.  I actually need this, but false is the correct default.

**Comment by rickerc** [comment]
I think we want false in puppet-openstack and true in grizzly-manifests - you guys fine with that?

**Comment by rickerc** [comment]
btw, @rakshithh just a small cosmetic change -- please line up the = and => in the rows you're adding with the rows around them

**Comment by iawells** [comment]
I think we want false in both.  I can't see why anyone would expect it to be true by default anywhere.  Certainly it will put us out of line with the way Openstack docs are written.

**Comment by rickerc** [comment]
@iawells because metadata is brain-dead and doesn't work with our targeted deployment scenarios?

**Comment by robertstarmer** [comment]
We probably need to provide guidance as to when to turn it in, and enabling it as a top level 'site.pp' variable makes sense. Leaving it as false for the bog standard deployment (i.e., single "external" network, l3_agent, gre on OVS) where meta-data works is ok.

On Aug 12, 2013, at 5:48 AM, Chris Ricker <notifications@github.com<mailto:notifications@github.com>>
 wrote:

@iawellshttps://github.com/iawells because metadata is brain-dead and doesn't work with our targeted deployment scenarios?

**Comment by iawells** [comment]
Metadata is brain-dead but, speaking as someone with a working Grizzly deployment, it definitely does work with some deployment scenarios.  (I have the API interface on the same subnet as the floating IPs, and that seems to make it work fine.)  More of an issue is that it's hard to set up the API interface independently from the (typically intentionally unreachable) internal network, though it can be done with a bit of work.  Probably more useful that we fix that.

Also, if you don't have a route from the VMs to the API server, then as well as losing metadata you lose the ability to call out to the API server from a VM which is pretty critical to any complex application.

**Comment by robertstarmer** [comment]
So do we have consensus:

Expose it up to site.pp (via core.pp via compute class), and leave it false across the board.

On Aug 12, 2013, at 9:24 AM, iawells <notifications@github.com<mailto:notifications@github.com>>
 wrote:

Metadata is brain-dead but, speaking as someone with a working Grizzly deployment, it definitely does work with some deployment scenarios. (I have the API interface on the same subnet as the floating IPs, and that seems to make it work fine.) More of an issue is that it's hard to set up the API interface independently from the (typically intentionally unreachable) internal network, though it can be done with a bit of work. Probably more useful that we fix that.

Also, if you don't have a route from the VMs to the API server, then as well as losing metadata you lose the ability to call out to the API server from a VM which is pretty critical to any complex application.

**Comment by danehans** [comment]
FYI:  https://review.openstack.org/#/c/41173/

**Comment by rakshithh** [comment]
closing the pull request as the patch https://review.openstack.org/#/c/41173/ is exactly what we wanted. Will be Exposing it up to site.pp (via core.pp via compute class). i wil be opening a new pull request with manifests

**Pull request closed without merging**
