### PR TITLE
Class memcached cause conflicts when running Swift proxy and storage on the same node

### PR DESCRIPTION
**Pull request by ghost**
...the same node.

Added and if statement to test if memcached is already declared elsewhere. If not, then it's declared.

### CODE REVIEW

**Comment by ghost** [comment]
don't merge this yet until we can confirm it's a legitimate bug

**Comment by robertstarmer** [comment]
And in reality, we really need to consider if we can't get ride of these meta modules anyway.

**Comment by markvoelker** [comment]
Should this go upstream?

**Comment by cbaesema** [comment]
why is it not breaking in AIO which runs swift proxy and storage on the same node? 

I see we disable it in AIO, this should go upstream it is a continuation of the duplicate class declaration fixes I placed in the module for AIO.

**Pull request closed without merging**
